### ISSUE TITLE
Error after uninstalling the addon from the project

### ISSUE THREAD

**Issue by Harikrishnadhas** [mariodavid/cuba-component-default-values#6]
Hi,

I'm getting below error after uninstalling the addon.

Caused by: java.lang.IllegalArgumentException: Datatype EntitySoftReference is not found
	at com.haulmont.cuba.core.sys.DatatypeRegistryImpl.get(DatatypeRegistryImpl.java:44) ~[cuba-global-7.2.13.jar:7.2.13]
	at com.haulmont.cuba.security.app.group.AccessGroupDefinitionsComposerImpl.lambda$composeGroupDefinitionFromDb$2(AccessGroupDefinitionsComposerImpl.java:119) ~[na:na]
	at com.haulmont.cuba.core.sys.TransactionImpl.execute(TransactionImpl.java:76) ~[na:na]
	at com.haulmont.cuba.core.sys.TransactionImpl.execute(TransactionImpl.java:70) ~[na:na]
	at com.haulmont.cuba.core.sys.PersistenceImpl.callInTransaction(PersistenceImpl.java:119) ~[na:na]
	at com.haulmont.cuba.security.app.group.AccessGroupDefinitionsComposerImpl.composeGroupDefinitionFromDb(AccessGroupDefinitionsComposerImpl.java:89) ~[na:na]
	at com.haulmont.cuba.security.sys.UserSessionManager.compileGroupDefinition(UserSessionManager.java:226) ~[na:na]
	at com.haulmont.cuba.security.sys.UserSessionManager.createSession(UserSessionManager.java:154) ~[na:na]
	at com.haulmont.cuba.security.auth.providers.AnonymousAuthenticationProvider.createSession(AnonymousAuthenticationProvider.java:108) ~[na:na]
	at com.haulmont.cuba.security.auth.providers.AnonymousAuthenticationProvider.authenticate(AnonymousAuthenticationProvider.java:79) ~[na:na]
	at com.haulmont.cuba.security.auth.AuthenticationManagerBean.authenticateInternal(AuthenticationManagerBean.java:252) ~[na:na]
	... 49 common frames omitted

Seems like while unintall it doesn't clean up propertly.

Thanks,
Hari

**Comment by Harikrishnadhas** [comment]
I had a session attribute configuration with EntitySoftReference  type. So I had installed the addon again and went and removed this session attribute.

And uninstalled the addon again.

Now started the server it is working now.

So it is the problem with referencing the EntitySoftReference which was present in this add on.
